version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: officeuser
      POSTGRES_PASSWORD: officepass
      POSTGRES_DB: officedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Mount initialization SQL (converted from single file). If you prefer a directory, create server/init-scripts and place files there.
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U officeuser -d officedb"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: ./server
    restart: always
    environment:
      DB_HOST: db
      DB_USER: officeuser
      DB_PASSWORD: officepass
      DB_NAME: officedb
      DB_PORT: 5432
      STATS_CACHE_TTL_MS: "30000"
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: nginx:alpine
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - app
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  pgdata:
